@startuml activity_library_after
|利用者|
start
repeat
  |利用者|
  :好きな作家の本を探す;
  |図書館システム|
  :蔵書を検索する;
  |利用者|
  :本を探す;
  :立ち読みする;
repeat while (面白いかどうか) is (面白くない)
-> 面白い;
|利用者|
:借りることに決める;
|図書館員|
:貸出手続きをする;
|図書館システム|
:貸出処理をする;
|利用者|
:本を受け取る;
end
@enduml