@startuml activity
|会員顧客|
start
:ログインする;
|ECサイト|
:おすすめを教える;
|会員顧客|
:注文する;
|ECサイト|
:受注手続きをする;
|カード会社|
:与信チェックを行う;

if () then (NG)
  |ECサイト|
  :与信エラーを通知する;
  end
else (OK)
  |ECサイト|
  :受注を確定する;
endif

|会員顧客|
:注文の結果を確認する;
end
@enduml