@startuml design
top to bottom direction
title クラスと関連の表現
class クラス1 {
   インスタンス変数
   インスタンス変数
   メソッド
   メソッド
   メソッド
}
note right : ギュッ
class クラス2 {
   インスタンス変数
   インスタンス変数
   メソッド
   メソッド
   メソッド
}
note right : ギュッ
class クラス3 {
   インスタンス変数
   インスタンス変数
   メソッド
   メソッド
   メソッド
}
note right : ギュッ

クラス1 <--> クラス2 : アッサリ
クラス1 <--> クラス3 : アッサリ
クラス2 <--> クラス3 : アッサリ
@enduml
