@startuml statemachine
title 状態遷移図のサンプル
[*] --> 受注受付
state 受注受付 {
    [*] --> 入荷待ち : [在庫なし]
    [*] --> 発送待ち : [在庫あり]
    入荷待ち --> 発送待ち : 入荷
}
受注受付 --> 発送完了 : 商品発送
発送完了 --> [*]

受注受付 --> キャンセル : 受注取消
キャンセル --> [*]
@enduml