@startuml usecase
left to right direction
actor 一般顧客
actor 会員顧客
actor 運用管理者
actor 配送業者

rectangle {
    一般顧客 --> (会員登録する)
    一般顧客 --> (商品を検索する)
    会員顧客 --> (商品を検索する)
    会員顧客 --> (発売前の商品を予約する)
    会員顧客 --> (商品を注文する)
    会員顧客 --> (注文内容を確認する)
    会員顧客 --> (配送状況を確認する)
    会員顧客 --> (注文をキャンセルする)
    (商品情報をメンテナンスする) <-- 運用管理者
    (ジャンル設定をメンテナンスする) <-- 運用管理者
    (配送状況を確認する) <-- 運用管理者
    (会員情報を照会する) <-- 運用管理者
    (売上を集計する) <-- 運用管理者
    (配送状況を確認する) <-- 配送業者
    (配送状況を更新する) <-- 配送業者
}
@enduml
